### ISSUE TITLE
Any Info about the purpose of this repo?

### ISSUE THREAD

**Issue by mahdyledurs** [BaldGod/PoocoinAnalyzer#1]
Can you please provide some infos about this repo? 
I checked the Code and there are serval lines that are very questionable

**Comment by savagebread** [comment]
Generates links for defi contracts. It is just a quality of life bot for when you want to share a contract or have it more readily accessible without putting in multiple contract links repeatedly. I don't know what about it makes it questionable. 
![image](https://user-images.githubusercontent.com/21990366/144250037-15773ac0-93c9-4d57-8469-975150cea27a.png)
